import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import ConvertkitSignupForm from '../components/ConvertkitSignupForm';

export default function Home() {
  return (
    <div className="bg-gray-900 text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>EduWeb3</h1>

        <p className={styles.description}>
          Lleva tu carrera en Web3 a otro nivel 🚀
        </p>

        <div className={styles.grid}>
          <ConvertkitSignupForm />
        </div>
      </main>
    </div>
  );
}
